# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bb \
	        ${LAYERDIR}/recipes-*/*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
            ${LAYERDIR}/recipes-*/*/*/*.bbappend"

# BBFILES_DYNAMIC += "\
#     mender:${LAYERDIR}/dynamic-layers/mender/*/*/*.bbappend \
# "

BBFILE_COLLECTIONS += "meta-mt-st"
BBFILE_PATTERN_meta-mt-st= "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-mt-st = "10"

LAYERDEPENDS_meta-mt-st = "core"
LAYERSERIES_COMPAT_meta-mt-st = "scarthgap"
